### ISSUE TITLE
Documentation re: read / write permissions

### ISSUE THREAD

**Issue by garbados** [hypercore-protocol/hyperbee#27]
Hypercores are not inherently mult-writer. As I understand it, multi-writer functionality must be implemented on top of hypercore. See [multifeed](https://github.com/kappa-db/multifeed)

But Hyperbee has no documentation about read / write capabilities. Is it possible to read and write to shared addresses?

**Comment by garbados** [comment]
What is the nature of that work? Orchestrating multiple writers on a shared object is fraught with nuance, especially in the context of writers that may not trust each other's writes (ex: any application with moderation requirements). Is there a place to follow along the details of this?

**Comment by Hedzer** [comment]
Is there any middleware at least to allow such a thing to be written?
maybe something like:
```
const db = new Hyperbee(feed, {
  keyEncoding: 'utf-8',
  valueEncoding: 'binary',
  access: {
      canSend: async (peer, key, value) => Promise<bool>,
      canReceive: async (peer, key, value) => Promise<bool>,
      mapSend: async (peer, key, value) => { peer, key, value },
      mapReceive: async (peer, key, value) => { peer, key, value },
  }
})

```

where canSend or canReceive resulting in false denies the action. This is me shooting from the hip here, so this might be named  very poorly, but the basic idea I think could be sound.

I also think that rather than encrypting stored values and giving users keys you could just encrypt values that are in-transit with the assumption that the user has access to the most current key. This would be a good way to be able to swap out leaked keys.

**Comment by mafintosh** [comment]
With autobase you can construct some elaborate multiwriter bees now :)
